import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Button, Container, Flex } from "@chakra-ui/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <Container display="flex" flexDirection="row">
            <Flex width="240px" height="100vh" flexDirection="column" gap="1" backgroundColor="gray.500">
              <Link href="/">
                <Button>메인 홈 화면</Button>
              </Link>
              <Link href="/login">
                <Button>로그인 화면</Button>
              </Link>
              <Link href="/logout">
                <Button>로그아웃 화면</Button>
              </Link>
              <Link href="/login/password-reset">
                <Button>비밀번호 재설정</Button>
              </Link>
              <Link href="/projects">
                <Button>프로젝트 종합 대시보드</Button>
              </Link>
              <Link href="/projects/project">
                <Button>프로젝트 개별 대시보드</Button>
              </Link>

              <Link href="/projects/project/tasks">
                <Button>업무관리 게시판</Button>
              </Link>

              <Link href="/projects/project/tasks/task">
                <Button>업무관리 게시글</Button>
              </Link>
              <Link href="/projects/project/approvals">
                <Button>프로젝트 결재 대시보드</Button>
              </Link>
              <Link href="/projects/project/approvals/approval">
                <Button>프로젝트 결재 게시글</Button>
              </Link>
            </Flex>
            {children}
          </Container>
        </Provider>
      </body>
    </html>
  );
}
