import type { Metadata } from "next";
import "./globals.css";

import { Provider } from "@/src/components/ui/provider";
import { Box, Container, Flex } from "@chakra-ui/react";
import Header from "@/src/components/layouts/Header";
import Sidebar from "@/src/components/layouts/Sidebar";
import { MSWComponent } from "@/src/components/common/MSWComponent";

export const metadata: Metadata = {
  title: "FlowSync",
  description: "Generated by create next app",
};

const RootLayout = (props: { children: React.ReactNode }) => {
  const { children } = props;
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <Header />
          <Container
            maxWidth={"100%"}
            display="flex"
            flexDirection="row"
            margin={0}
            padding={0}
          >
            <Sidebar />
            <Flex
              width="100%"
              height="100%"
              align="center"
              justify="center"
              bg="gray.50"
              p={6}
            >
              <Box
                maxW="container.xl"
                width="100%"
                bg="white"
                borderRadius="lg"
                p={8}
              >
                <MSWComponent>{children}</MSWComponent>
              </Box>
            </Flex>
          </Container>
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
